### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-clickhouse#105]
This project does not seem to have an active maintainer. There are a couple of open PRs from @nickbp and @bocharovf. Is anybody of you willing to take part in the project and maintain it? 

cc) @EinKrebs

**Comment by nickbp** [comment]
I'm available. We're actively using jaeger-clickhouse for new tracing support within Opstrace and I'm expecting we'll have a steady stream of improvements and fixes (like #104) as we're running it.

**Comment by bocharovf** [comment]
I'm interested too. We currently try to migrate from elasticsearch to clickhouse storage. So there could be more PRs from me...

**Comment by pavolloffay** [comment]
thanks, I will add you both to the project. Please take care of it :)

**Comment by pavolloffay** [comment]
To avoid any conflicts, please prioritize merging approved PRs :)

**Comment by dnsmichi** [comment]
I'll subscribe to this project and try to learn and contribute, as we progress with Opstrace. Thanks @nickbp @bocharovf for stepping up! ❤️
