### ISSUE TITLE
[Bug]: System Architecture reported an error when I used Click House as the storage backend

### ISSUE THREAD

**Issue by zenvzenv** [jaegertracing/jaeger-clickhouse#131]
### What happened?

System Architecture reported an error when I used ClickHouse as the storage backend,the error like this:
```text
HTTP Error: plugin error:rpc error: code = Unknown desc = not implemented
```

### Steps to reproduce

1. Use ClickHouse as the storage,the cmd is : SPAN_STROAGE_TYPE=grpc-plugin jaeger-all-in-one --grpc.stroage.plugin.binary=/path/to/jaeger-clickhouse-linux-amd64 --grpc.stroage.configuration=/path/to/config.yml
2. start up jaeger
3. click "System Architecture" report a error,like this : 
    ```text
    HTTP Error: plugin error:rpc error: code = Unknown desc = not implemented
    ```

### Expected behavior

I expect System Architecture to display a DAG of the calling relationship of each system

### Jaeger backend version

1.47.0

### SDK

OpenTelemetry javaagent 1.28.0

### Pipeline

javaagent->otelcol->jaeger

### Stogage backend

clickhouse

### Operating system

linux

### Deployment model

CLI

**Comment by selfing12** [comment]
@pavolloffay
