### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-clickhouse#5]
Add integration test that spins up ClickHouse, Jaeger with storage plugin. The test would store and query data.

Jaeger already has storage integration tests - https://github.com/jaegertracing/jaeger/tree/master/plugin/storage/integration. It would be great if they could be reused.

**Comment by pavolloffay** [comment]
I am working on this one now

**Comment by EinKrebs** [comment]
@pavolloffay Should we close this issue?

**Comment by pavolloffay** [comment]
no, we need similar tests that verify query compatibility like in the link above. 

It would be also great to create a test for replicated deployment.
