### ISSUE TITLE
Add Operation.SpanKind support

### ISSUE THREAD

**Issue by EinKrebs** [jaegertracing/jaeger-clickhouse#76]
## Requirement - what kind of business use case are you trying to solve?

I ran jaeger grpc-plugin integration tests with this plugin and it failed.

## Problem - what in Jaeger blocks you from solving the requirement?

Integration test failed because this plugin doesn't support jaeger/spanstore.Operation.SpanKind.

**Comment by EinKrebs** [comment]
I think it's needed to store tag keys separate from values in index table. @pavolloffay is this okay?

**Comment by pavolloffay** [comment]
> Integration test failed because this plugin doesn't support jaeger/spanstore.Operation.SpanKind.

What do you exactly mean by this? The storage plugin wasn't able to query data based on the span kind? It's an implementation detail how the span kind will be queried.

**Comment by EinKrebs** [comment]
> What do you exactly mean by this? 

Jaeger wrote spans with span.kind tag, but GetOperations retrieved operations with empty SpanKind field.

**Comment by EinKrebs** [comment]
It's not necessary to implement this by now, but I guess it's better to do this anyway.
