### ISSUE TITLE
Search by error tag does not work

### ISSUE THREAD

**Issue by bocharovf** [jaegertracing/jaeger-clickhouse#98]
**Describe the bug**
Filter "error=true" does not show traces with errors. 

**To Reproduce**
1. Use clickhouse storage plugin
2. Run HotROD and produce some traces
3. In Jaeger UI select "Redis" service and find traces. Check that there are traces with errors in Redis service.
4. Add Tags filter "error=true"
5. See "No trace results. Try another query."

**Expected behavior**
Traces with Redis error found

**Screenshots**
<img width="727" alt="there are errors in traces" src="https://user-images.githubusercontent.com/5367465/137553204-db294b09-28f6-4c27-a1c1-2d9cc69f4c70.PNG">

<img width="576" alt="errors are in Redis" src="https://user-images.githubusercontent.com/5367465/137553222-2e5012d5-be06-4eb8-b3f2-279b24c4432b.PNG">

<img width="652" alt="Redis errors not found" src="https://user-images.githubusercontent.com/5367465/137553240-cd9a51f9-c1e7-4082-a80e-3628aed1c990.PNG">

**Version (please complete the following information):**
 - OS: windows
 - Jaeger version: 1.27
 - Deployment: docker-compose
 - Clickhouse plugin version: 0.8
 - Clickhouse version: yandex/clickhouse-server:21

**What troubleshooting steps did you try?**
Tag filter works as expected with another tags (e.g. "param.driverID").  
Error tag filter works with Elasticsearch plugin.

I use that [docker-compose](https://gist.github.com/bocharovf/a151e2bfc657804c966fa9763c7ded8b) to compare ELK and Clickhouse storages.

**Comment by rlex** [comment]
Same issue. http.status_code=200 works fine, error=true returns empty results. Tested with jaeger hotrod.

**Comment by bocharovf** [comment]
Root cause: there could be more than one tag with the same name in tags.key / tags.value columns of jaeger_index_local table but we only check the first occurrence of it. This is because we also serialize events (logs) into tags.* column. 

So we end up with multiple "error" tag:
```
client-uuid=534bc4dfd268070c
driver_id=T762908C
error=redis timeout
error=true
...
span.kind=client
```
![image](https://user-images.githubusercontent.com/5367465/143784021-c825f02d-f447-49b9-bb0b-0d97e24a4e7c.png)

And only first value could be found because we use filter `tags.value[indexOf(tags.key, ?)] == ?`
![image](https://user-images.githubusercontent.com/5367465/143783912-4ce85b48-14f6-4493-9617-bf600c752f77.png)

Seems there is no easy way to get all array indexes of values so it's hard to check all tag values.

Should we really support searching for events (log) attributes? 
We could either stop serialize them into tags columns or at least prefix with "event." to distinguish from boolean error tag.
